version: "3.8"

services:
  app:
    build: .
    command: npm start
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: mysql:latest
    restart: always
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: $DB_PASS
    volumes:
      - /mysql-data:/var/lib/mysql
      - ./db-script.sql:/docker-entrypoint-initdb.d/db-script.sql
    ports:
      - '3306:3306'
    cap_add:
      - SYS_NICE